[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Archive"
  identifier = "Archive"
  weight = -109

[[main]]
  parent = "Archive"
  name = "2023"
  weight = -12
  url = "/archive/2023/"
[[main]]
  parent = "Archive"
  name = "2022"
  weight = -11
  url = "/archive/2022/"
[[main]]
  parent = "Archive"
  name = "2021"
  weight = -10
  url = "/archive/2021/"
[[main]]
  parent = "Archive"
  name = "2020"
  weight = -9
  url = "/archive/2020/"
[[main]]
  parent = "Archive"
  name = "2019"
  weight = -8
  url = "/archive/2019/"
[[main]]
  parent = "Archive"
  name = "2017"
  weight = -7
  url = "/archive/2017/"
[[main]]
  parent = "Archive"
  name = "2016"
  weight = -6
  url = "/archive/2016/"
[[main]]
  parent = "Archive"
  name = "2015"
  weight = -5
  url = "/archive/2015/"
[[main]]
  parent = "Archive"
  name = "2014"
  weight = -4
  url = "/archive/2014/"
[[main]]
  parent = "Archive"
  name = "2013"
  weight = -3
  url = "/archive/2013/"
[[main]]
  parent = "Archive"
  name = "2012"
  weight = -2
  url = "/archive/2012/"
[[main]]
  parent = "Archive"
  name = "2011"
  weight = -1
  url = "/archive/2011/"

[[main]]
  name = "Links"
  identifier = "Links"
  weight = -108
[[main]]
  parent = "Links"
  name = "LinkedIn"
  url = "https://linkedin.com/in/garyjblake"
[[main]]
  parent = "Links"
  name = "Twitter"
  url = "https://twitter.com/garyjblake"

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/garyjblake"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/garyjblake"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://uk.linkedin.com/in/garyjblake"
  
# other supported social links
# name = "rss"
# url = "index.xml"
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"